-- Genera el DDL completo del schema `public` desde el catalogo de produccion.
-- Cada fila = un fragmento; `ord` define el orden de emision.
--
-- v2 (2026-07-29): agrega lo que faltaba en v1 y que rompia la fidelidad del
-- baseline — ACLs (ord 97), publicaciones de Realtime (98), comentarios (99),
-- reloptions de tablas (31) y parametros completos de secuencias (20).
WITH
-- Objetos que PERTENECEN a una extension: los recrea `CREATE EXTENSION`, no el
-- baseline. Son las 31 funciones de pg_trgm en `public`, cuyo dueño es
-- supabase_admin — un CREATE OR REPLACE sobre ellas o las saca de la extension
-- o falla por permisos, y un GRANT/REVOKE falla porque no somos el dueño.
-- (Verificado: ninguna tabla/vista/secuencia de `public` es miembro de extension.)
miembros_ext AS (
  SELECT d.objid, d.classid
  FROM pg_depend d
  WHERE d.deptype = 'e' AND d.refclassid = 'pg_extension'::regclass
),
ext AS (
  -- `k`::text a proposito: es la primera rama del UNION y por lo tanto fija el
  -- tipo de la columna para todas las demas. Con `extname` (tipo `name`) el
  -- resto se casteaba a `name` y se truncaba a 63 chars — 188 claves colisionaban
  -- y el ORDER BY quedaba ambiguo entre overloads.
  SELECT 10 AS ord, e.extname::text AS k,
         'CREATE EXTENSION IF NOT EXISTS '||quote_ident(e.extname)||
         ' WITH SCHEMA '||quote_ident(n.nspname)||';' AS ddl
  FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace
  WHERE e.extname NOT IN ('plpgsql')
),
-- Secuencias NO ligadas a una columna IDENTITY (esas las recrea la propia
-- clausula GENERATED ... AS IDENTITY del CREATE TABLE). Las de tipo `serial`
-- si van aca, porque su dependencia es AUTO ('a') y el DEFAULT nextval() de la
-- tabla las necesita ya creadas.
seqs AS (
  SELECT 20 AS ord, c.relname AS k,
         'CREATE SEQUENCE IF NOT EXISTS public.'||quote_ident(c.relname)||
         ' AS '||format_type(s.seqtypid,NULL)||
         ' INCREMENT BY '||s.seqincrement||
         ' MINVALUE '||s.seqmin||
         ' MAXVALUE '||s.seqmax||
         ' START WITH '||s.seqstart||
         ' CACHE '||s.seqcache||
         CASE WHEN s.seqcycle THEN ' CYCLE' ELSE ' NO CYCLE' END||';' AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid=c.relnamespace
  JOIN pg_sequence s ON s.seqrelid=c.oid
  WHERE n.nspname='public' AND c.relkind='S'
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid=c.oid AND d.deptype='i')
),
tbls AS (
  SELECT 30 AS ord, c.relname AS k,
    'CREATE TABLE public.'||quote_ident(c.relname)||' ('||E'\n  '||
    string_agg(
      quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod)
      || CASE WHEN a.attgenerated='s'
              THEN ' GENERATED ALWAYS AS ('||pg_get_expr(ad.adbin,ad.adrelid)||') STORED'
              WHEN a.attidentity='d' THEN ' GENERATED BY DEFAULT AS IDENTITY'
              WHEN a.attidentity='a' THEN ' GENERATED ALWAYS AS IDENTITY'
              WHEN ad.adbin IS NOT NULL
              THEN ' DEFAULT '||pg_get_expr(ad.adbin,ad.adrelid)
              ELSE '' END
      || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
    , E',\n  ' ORDER BY a.attnum)||E'\n);' AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid=c.relnamespace
  JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef ad ON ad.adrelid=c.oid AND ad.adnum=a.attnum
  WHERE n.nspname='public' AND c.relkind='r'
  GROUP BY c.relname
),
-- Storage parameters por tabla (hoy: autovacuum agresivo en las dos tablas de
-- ventas). Se pierde en silencio si no se emite.
tbl_opts AS (
  SELECT 31 AS ord, c.relname AS k,
    'ALTER TABLE public.'||quote_ident(c.relname)||
    ' SET ('||array_to_string(c.reloptions,', ')||');' AS ddl
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind='r' AND c.reloptions IS NOT NULL
),
-- ord 25: las funciones van ANTES de las tablas. Cinco tablas tienen columnas
-- `GENERATED ALWAYS AS (norm_search(...)) STORED` o defaults que llaman a una
-- funcion de `public`, y el CREATE TABLE falla si la funcion no existe todavia.
-- Es seguro porque `check_function_bodies = off` permite que el cuerpo referencie
-- tablas inexistentes, y porque CERO funciones tienen un tipo de tabla en su
-- firma (medido) — o sea no hay dependencia circular.
-- ord 32: renombrar las secuencias de columnas IDENTITY cuyo nombre real no es
-- el que Postgres autogenera. Pasa cuando la tabla se renombro: `ALTER TABLE
-- ... RENAME` NO renombra la secuencia asociada, asi que el nombre viejo queda
-- fosilizado. Caso real: prod tiene `product_presentations_id_seq` para
-- `product_precios.id`. Sin esto la secuencia queda con otro nombre y encima
-- fallan sus GRANT de la seccion de privilegios.
seq_rename AS (
  SELECT 32 AS ord, s.real AS k,
    'ALTER SEQUENCE public.'||quote_ident(s.autogenerado)||
    ' RENAME TO '||quote_ident(s.real)||';' AS ddl
  FROM (
    SELECT c.relname AS real,
           left(t.relname||'_'||a.attname||'_seq', 63) AS autogenerado
    FROM pg_class c
    JOIN pg_namespace n ON n.oid=c.relnamespace
    JOIN pg_depend d ON d.objid=c.oid AND d.classid='pg_class'::regclass
                    AND d.deptype='i'
    JOIN pg_class t ON t.oid=d.refobjid
    JOIN pg_attribute a ON a.attrelid=t.oid AND a.attnum=d.refobjsubid
    WHERE n.nspname='public' AND c.relkind='S'
  ) s
  WHERE s.real <> s.autogenerado
),
funcs AS (
  SELECT 25 AS ord, p.proname||'('||pg_get_function_identity_arguments(p.oid)||')' AS k,
         pg_get_functiondef(p.oid)||';' AS ddl
  FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
  WHERE n.nspname='public' AND p.prokind IN ('f','p')
    AND NOT EXISTS (SELECT 1 FROM miembros_ext m
                    WHERE m.objid=p.oid AND m.classid='pg_proc'::regclass)
),
-- Las matviews van WITH NO DATA a proposito: poblarlas ejecuta su query, y en
-- una base recien creada eso puede fallar por dependencias de runtime. El
-- baseline define esquema, no datos; se refrescan despues.
-- OJO: pg_get_viewdef() ya termina en ';', asi que hay que quitarlo antes de
-- pegarle WITH NO DATA — si no, queda como sentencia suelta y es syntax error.
vws AS (
  SELECT 50 AS ord, c.relname AS k,
    CASE WHEN c.relkind='m'
      THEN 'CREATE MATERIALIZED VIEW public.'||quote_ident(c.relname)||
           CASE WHEN c.reloptions IS NOT NULL
                THEN ' WITH ('||array_to_string(c.reloptions,', ')||')' ELSE '' END||
           ' AS '||regexp_replace(pg_get_viewdef(c.oid), ';\s*$', '')||
           E'\nWITH NO DATA;'
      ELSE 'CREATE OR REPLACE VIEW public.'||quote_ident(c.relname)||
           CASE WHEN c.reloptions IS NOT NULL
                THEN ' WITH ('||array_to_string(c.reloptions,', ')||')' ELSE '' END||
           ' AS '||pg_get_viewdef(c.oid)
    END AS ddl
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind IN ('v','m')
),
cons_pk AS (
  SELECT 60 AS ord, c.relname||con.conname AS k,
    'ALTER TABLE public.'||quote_ident(c.relname)||' ADD CONSTRAINT '||
    quote_ident(con.conname)||' '||pg_get_constraintdef(con.oid)||';' AS ddl
  FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND con.contype IN ('p','u')
),
cons_rest AS (
  SELECT 70 AS ord, c.relname||con.conname AS k,
    'ALTER TABLE public.'||quote_ident(c.relname)||' ADD CONSTRAINT '||
    quote_ident(con.conname)||' '||pg_get_constraintdef(con.oid)||';' AS ddl
  FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND con.contype IN ('f','c')
),
idx AS (
  SELECT 80 AS ord, c.relname AS k, pg_get_indexdef(i.indexrelid)||';' AS ddl
  FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid
  JOIN pg_class t ON t.oid=i.indrelid
  JOIN pg_namespace n ON n.oid=t.relnamespace
  WHERE n.nspname='public'
    AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=i.indexrelid)
),
trg AS (
  SELECT 90 AS ord, t.tgname AS k, pg_get_triggerdef(t.oid)||';' AS ddl
  FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND NOT t.tgisinternal
),
rls AS (
  SELECT 95 AS ord, c.relname AS k,
    'ALTER TABLE public.'||quote_ident(c.relname)||' ENABLE ROW LEVEL SECURITY;'||
    CASE WHEN c.relforcerowsecurity
         THEN E'\nALTER TABLE public.'||quote_ident(c.relname)||' FORCE ROW LEVEL SECURITY;'
         ELSE '' END AS ddl
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind='r' AND c.relrowsecurity
),
pol AS (
  SELECT 96 AS ord, c.relname||pol.polname AS k,
    'CREATE POLICY '||quote_ident(pol.polname)||' ON public.'||quote_ident(c.relname)||
    ' AS '||CASE WHEN pol.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END||
    ' FOR '||CASE pol.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT'
                             WHEN 'w' THEN 'UPDATE' WHEN 'd' THEN 'DELETE'
                             ELSE 'ALL' END||
    ' TO '||coalesce((SELECT string_agg(quote_ident(rolname),', ' ORDER BY rolname)
                      FROM pg_roles WHERE oid = ANY(pol.polroles)),'PUBLIC')||
    coalesce(' USING ('||pg_get_expr(pol.polqual,pol.polrelid)||')','')||
    coalesce(' WITH CHECK ('||pg_get_expr(pol.polwithcheck,pol.polrelid)||')','')||';' AS ddl
  FROM pg_policy pol JOIN pg_class c ON c.oid=pol.polrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public'
),
-- ── ACLs ────────────────────────────────────────────────────────────────────
-- CRITICO: en `public` hay ALTER DEFAULT PRIVILEGES que otorga ALL a
-- anon/authenticated/service_role sobre cada tabla y funcion nueva. Sin este
-- bloque, reconstruir el esquema reabre exactamente la superficie de `anon` que
-- el proyecto cerro (CLAUDE.md regla #4). Por eso cada objeto lleva primero un
-- REVOKE ALL y despues los GRANT exactos que tiene produccion.
acl_rel_raw AS (
  SELECT c.relname,
         CASE WHEN c.relkind='S' THEN 'SEQUENCE' ELSE 'TABLE' END AS kw,
         coalesce(r.rolname,'PUBLIC') AS grantee,
         a.privilege_type
  FROM pg_class c
  JOIN pg_namespace n ON n.oid=c.relnamespace
  CROSS JOIN LATERAL aclexplode(c.relacl) a
  LEFT JOIN pg_roles r ON r.oid=a.grantee
  WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','S')
    AND c.relacl IS NOT NULL
),
acl_rel_g AS (
  SELECT relname, kw, grantee,
         string_agg(privilege_type, ', ' ORDER BY privilege_type) AS privs
  FROM acl_rel_raw GROUP BY relname, kw, grantee
),
acl_rel AS (
  SELECT 97 AS ord, '1rel:'||relname AS k,
    'REVOKE ALL ON '||kw||' public.'||quote_ident(relname)||
    ' FROM PUBLIC, anon, authenticated, service_role;'||E'\n'||
    string_agg('GRANT '||privs||' ON '||kw||' public.'||quote_ident(relname)||
               ' TO '||CASE WHEN grantee='PUBLIC' THEN 'PUBLIC'
                            ELSE quote_ident(grantee) END||';',
               E'\n' ORDER BY grantee) AS ddl
  FROM acl_rel_g GROUP BY relname, kw
),
acl_fn_raw AS (
  SELECT CASE WHEN p.prokind='p' THEN 'PROCEDURE' ELSE 'FUNCTION' END AS kw,
         'public.'||quote_ident(p.proname)||'('||
           pg_get_function_identity_arguments(p.oid)||')' AS sig,
         coalesce(r.rolname,'PUBLIC') AS grantee,
         a.privilege_type
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid=p.pronamespace
  CROSS JOIN LATERAL aclexplode(p.proacl) a
  LEFT JOIN pg_roles r ON r.oid=a.grantee
  WHERE n.nspname='public' AND p.prokind IN ('f','p') AND p.proacl IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM miembros_ext m
                    WHERE m.objid=p.oid AND m.classid='pg_proc'::regclass)
),
acl_fn_g AS (
  SELECT kw, sig, grantee,
         string_agg(privilege_type, ', ' ORDER BY privilege_type) AS privs
  FROM acl_fn_raw GROUP BY kw, sig, grantee
),
acl_fn AS (
  SELECT 97 AS ord, '2fn:'||sig AS k,
    'REVOKE ALL ON '||kw||' '||sig||
    ' FROM PUBLIC, anon, authenticated, service_role;'||E'\n'||
    string_agg('GRANT '||privs||' ON '||kw||' '||sig||
               ' TO '||CASE WHEN grantee='PUBLIC' THEN 'PUBLIC'
                            ELSE quote_ident(grantee) END||';',
               E'\n' ORDER BY grantee) AS ddl
  FROM acl_fn_g GROUP BY kw, sig
),
-- ── Publicaciones (Realtime) ────────────────────────────────────────────────
-- Membresia en supabase_realtime. Idempotente: no falla si la publicacion ya
-- existe ni si la tabla ya es miembro.
pub_def AS (
  SELECT 98 AS ord, '1pub:'||pb.pubname AS k,
    'DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname='||
    quote_literal(pb.pubname)||') THEN CREATE PUBLICATION '||
    quote_ident(pb.pubname)||' WITH (publish='||
    quote_literal(concat_ws(', ',
      CASE WHEN pb.pubinsert   THEN 'insert'   END,
      CASE WHEN pb.pubupdate   THEN 'update'   END,
      CASE WHEN pb.pubdelete   THEN 'delete'   END,
      CASE WHEN pb.pubtruncate THEN 'truncate' END))||'); END IF; END $do$;' AS ddl
  FROM pg_publication pb
  WHERE EXISTS (
    SELECT 1 FROM pg_publication_rel pr
    JOIN pg_class c ON c.oid=pr.prrelid
    JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE pr.prpubid=pb.oid AND n.nspname='public')
),
pub_rel AS (
  SELECT 98 AS ord, '2pubrel:'||pb.pubname||':'||c.relname AS k,
    'DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_rel pr '||
    'JOIN pg_publication pb ON pb.oid=pr.prpubid '||
    'JOIN pg_class c ON c.oid=pr.prrelid '||
    'JOIN pg_namespace n ON n.oid=c.relnamespace '||
    'WHERE pb.pubname='||quote_literal(pb.pubname)||
    ' AND n.nspname=''public'' AND c.relname='||quote_literal(c.relname)||
    ') THEN ALTER PUBLICATION '||quote_ident(pb.pubname)||
    ' ADD TABLE ONLY public.'||quote_ident(c.relname)||'; END IF; END $do$;' AS ddl
  FROM pg_publication_rel pr
  JOIN pg_class c ON c.oid=pr.prrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  JOIN pg_publication pb ON pb.oid=pr.prpubid
  WHERE n.nspname='public'
),
-- ── Comentarios ─────────────────────────────────────────────────────────────
com_rel AS (
  SELECT 99 AS ord, '1rel:'||c.relname AS k,
    'COMMENT ON '||CASE c.relkind WHEN 'v' THEN 'VIEW'
                                  WHEN 'm' THEN 'MATERIALIZED VIEW'
                                  WHEN 'S' THEN 'SEQUENCE'
                                  ELSE 'TABLE' END||
    ' public.'||quote_ident(c.relname)||' IS '||quote_literal(d.description)||';' AS ddl
  FROM pg_description d
  JOIN pg_class c ON c.oid=d.objoid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND d.objsubid=0 AND c.relkind IN ('r','p','v','m','S')
),
com_col AS (
  SELECT 99 AS ord, '2col:'||c.relname||'.'||a.attname AS k,
    'COMMENT ON COLUMN public.'||quote_ident(c.relname)||'.'||
    quote_ident(a.attname)||' IS '||quote_literal(d.description)||';' AS ddl
  FROM pg_description d
  JOIN pg_class c ON c.oid=d.objoid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=d.objsubid
  WHERE n.nspname='public' AND d.objsubid>0 AND NOT a.attisdropped
),
com_fn AS (
  SELECT 99 AS ord, '3fn:'||p.proname AS k,
    'COMMENT ON '||CASE WHEN p.prokind='p' THEN 'PROCEDURE' ELSE 'FUNCTION' END||
    ' public.'||quote_ident(p.proname)||'('||
    pg_get_function_identity_arguments(p.oid)||') IS '||
    quote_literal(d.description)||';' AS ddl
  FROM pg_description d
  JOIN pg_proc p ON p.oid=d.objoid
  JOIN pg_namespace n ON n.oid=p.pronamespace
  WHERE n.nspname='public' AND p.prokind IN ('f','p')
),
todo AS (
  SELECT * FROM ext        UNION ALL SELECT * FROM seqs
  UNION ALL SELECT * FROM tbls       UNION ALL SELECT * FROM tbl_opts
  UNION ALL SELECT * FROM seq_rename
  UNION ALL SELECT * FROM funcs      UNION ALL SELECT * FROM vws
  UNION ALL SELECT * FROM cons_pk    UNION ALL SELECT * FROM cons_rest
  UNION ALL SELECT * FROM idx        UNION ALL SELECT * FROM trg
  UNION ALL SELECT * FROM rls        UNION ALL SELECT * FROM pol
  UNION ALL SELECT * FROM acl_rel    UNION ALL SELECT * FROM acl_fn
  UNION ALL SELECT * FROM pub_def    UNION ALL SELECT * FROM pub_rel
  UNION ALL SELECT * FROM com_rel    UNION ALL SELECT * FROM com_col
  UNION ALL SELECT * FROM com_fn
)
SELECT ord, k, ddl FROM todo ORDER BY ord, k;
