// El catálogo de permisos — la mitad de la INTERFAZ.
//
// El catálogo vive en el núcleo (`constants/permissionModules.js`) con cada ícono por NOMBRE
// (`icono: 'Home'`), porque una app nativa no puede reutilizar un catálogo que
// trae adentro componentes de la web. Esto le pone los componentes de
// `lucide-react` y entrega la MISMA API de siempre —las pantallas sólo cambian
// de dónde la importan—. Importa exactamente los íconos que importaba el
// catálogo, así ninguna pantalla carga más que antes. Enfrentado entrada por
// entrada contra la versión anterior: mismo componente. Plan en
// `docs/PLAN-NUCLEO-PORTABLE-2026-09-24.md`.
import {
    HandCoins,
    CalendarCheck,
    ShieldCheck,
    Monitor,
    Calendar,
    Building2,
    Megaphone,
    ClipboardList,
    Palmtree,
    Activity,
    AlertTriangle,
    User,
    Eye,
    Pencil,
    CheckCircle2,
    Lock,
    Unlock,
    Save,
    RotateCcw,
    ChevronRight,
    Loader2,
    Check,
    X,
    ShieldAlert,
    Info,
    Home,
    Bell,
    FolderOpen,
    Zap,
    Copy,
    Search,
    MousePointerClick,
    TrendingUp,
    Briefcase,
    CalendarDays,
    PieChart,
    BarChart2,
    UserX,
    Clock,
    Gift,
    DollarSign,
    FileText,
    Package,
    Receipt,
    Target,
    FlaskConical,
    Smartphone,
    Sparkles,
    Layers,
    Globe2,
    BadgeAlert,
    PackageMinus,
    ShoppingCart,
    ClipboardCheck,
    RadioTower,
    Ghost,
    Truck,
    Boxes,
    MonitorSmartphone,
    ShieldOff,
    BookOpen,
    Contact,
    Wrench,
    Users,
    Calculator,
    ReceiptText,
    Printer,
    Wallet,
    Landmark,
    PackagePlus,
    Thermometer,
    Pill,
    Mail,
    Star,
} from 'lucide-react';
import { MODULE_GROUPS as GRUPOS, MODULE_INFO as INFO } from '../../../constants/permissionModules';

export * from '../../../constants/permissionModules';

const ICONOS = {
    Activity,
    AlertTriangle,
    BadgeAlert,
    BarChart2,
    Bell,
    BookOpen,
    Boxes,
    Briefcase,
    Building2,
    Calculator,
    Calendar,
    CalendarCheck,
    CalendarDays,
    Check,
    CheckCircle2,
    ChevronRight,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Contact,
    Copy,
    DollarSign,
    Eye,
    FileText,
    FlaskConical,
    FolderOpen,
    Ghost,
    Gift,
    Globe2,
    HandCoins,
    Home,
    Info,
    Landmark,
    Layers,
    Loader2,
    Lock,
    Mail,
    Megaphone,
    Monitor,
    MonitorSmartphone,
    MousePointerClick,
    Package,
    PackageMinus,
    PackagePlus,
    Palmtree,
    Pencil,
    PieChart,
    Pill,
    Printer,
    RadioTower,
    Receipt,
    ReceiptText,
    RotateCcw,
    Save,
    Search,
    ShieldAlert,
    ShieldCheck,
    ShieldOff,
    ShoppingCart,
    Smartphone,
    Sparkles,
    Target,
    Thermometer,
    TrendingUp,
    Truck,
    Unlock,
    User,
    UserX,
    Users,
    Wallet,
    Wrench,
    X,
    Zap,
    Star,
};

// Le agrega `.icon` a todo objeto del catálogo que tenga `icono`, a cualquier
// profundidad (los módulos traen sub-permisos adentro).
const conIconos = (v) => {
    if (Array.isArray(v)) return v.map(conIconos);
    if (v && typeof v === 'object' && Object.getPrototypeOf(v) === Object.prototype) {
        const o = Object.fromEntries(Object.entries(v).map(([k, x]) => [k, conIconos(x)]));
        if (typeof v.icono === 'string') o.icon = ICONOS[v.icono];
        return o;
    }
    return v;
};

export const MODULE_GROUPS = conIconos(GRUPOS);
export const MODULE_INFO = conIconos(INFO);
