// Sinónimos/palabras clave por módulo para el buscador del menú (Cmd/Ctrl+K).
// No repite el label (ya se busca solo) — solo términos con los que un
// usuario real buscaría sin saber el nombre exacto del módulo.
export const MODULE_SEARCH_KEYWORDS = {
    overview:           ['inicio', 'resumen', 'panorama general', 'bienvenida'],
    emp_requests:       ['solicitudes propias', 'permisos personales', 'vacaciones propias'],
    emp_announcements:  ['comunicados', 'avisos internos'],
    emp_profile:        ['datos personales', 'mi cuenta', 'mi informacion'],
    emp_documents:      ['incapacidades', 'constancias', 'documentos personales'],
    staff_list:         ['empleados', 'personal', 'fichas de empleados', 'directorio', 'expediente'],
    monitor:            ['asistencia en tiempo real', 'quien esta trabajando', 'presentes hoy'],
    time_audit:         ['tardanzas', 'faltas', 'puntualidad', 'ausentismo'],
    schedules:          ['turnos', 'horarios de trabajo', 'roster'],
    requests:           ['solicitudes de empleados', 'aprobar permisos', 'vacaciones pendientes'],
    vacation_plan:      ['vacaciones', 'plan anual de vacaciones', 'dias disponibles'],
    payroll:            ['planilla', 'salarios', 'sueldos', 'ingresos del empleado'],
    branches:           ['sucursales', 'locales', 'tiendas', 'farmacias'],
    roles:              ['cargos', 'organigrama', 'puestos', 'jerarquia'],
    announcements:      ['comunicados', 'avisos internos', 'notificar empleados'],
    permissions:        ['roles y permisos', 'accesos', 'configuracion de accesos'],
    auditview:          ['bitacora', 'logs', 'historial de acciones'],
    ios_test:           ['prueba de app movil'],
    sync_health:        ['estado de sincronizacion', 'cron', 'erp sync', 'salud del sistema'],
    orphan_objects:     ['archivos huerfanos', 'storage sin usar', 'limpieza'],
    ventas:             ['venta de productos', 'ingresos', 'facturacion diaria', 'ventas por sucursal'],
    metas:              ['objetivos', 'kpis de ventas', 'target de ventas'],
    facturacion:        ['dte', 'documentos tributarios electronicos', 'anulaciones', 'no efectivo'],
    cotizaciones:       ['presupuestos', 'ofertas a clientes'],
    encuesta:           ['clima laboral', 'satisfaccion del empleado'],
    encuesta_admin:     ['gestionar encuestas', 'crear encuesta'],
    promociones:        ['descuentos', 'ofertas especiales', 'promos'],
    bonificaciones:     ['incentivos', 'comisiones', 'bonos'],
    entrevistas:        ['reclutamiento', 'candidatos', 'contratacion'],
    productos:          ['catalogo', 'medicamentos', 'articulos', 'presentaciones', 'ficha de producto'],
    laboratorios:       ['fabricantes', 'marcas', 'labs'],
    pedidos:            ['logistica', 'traslados entre sucursales', 'reabastecimiento', 'distribucion interna'],
    minmax:             ['min max', 'stock', 'reposicion', 'existencias', 'punto de reorden'],
    ventas_perdidas:    ['quiebres de stock', 'sin stock', 'faltantes', 'stockouts'],
    compras:            ['compras del erp', 'facturas de bodega', 'costos de compra'],
    facturas_compra:    ['facturas de proveedores', 'correo de facturas', 'dte de compras', 'gastos'],
    proveedores:        ['suppliers', 'contactos de proveedor', 'maestro de proveedores'],
    conteo_inventario:  ['auditoria de inventario', 'conteo fisico', 'cuadre de stock'],
};
