-- Bloque 7B.7: registro manual versionado de "objetos huérfanos" — candidatos
-- de código muerto ya encontrados en sesiones pasadas (o durante esta), para
-- que puedan marcarse como revisados/eliminados/falso-positivo desde la UI
-- sin tocar código. No es un escáner automático (el proyecto no tiene
-- knip/ts-prune corriendo) — es un tablero de seguimiento.

SET lock_timeout = '5s';

CREATE TABLE public.orphan_objects_registry (
  id           bigint generated by default as identity primary key,
  kind         text not null,
  ref          text not null,
  title        text not null,
  status       text not null default 'candidate'
               check (status in ('candidate','confirmed_orphan','false_positive','resolved')),
  detected_at  timestamptz not null default now(),
  resolved_at  timestamptz,
  notes        text,
  created_at   timestamptz not null default now()
);

ALTER TABLE public.orphan_objects_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "orphan_objects_registry_select" ON public.orphan_objects_registry
  FOR SELECT TO authenticated
  USING ((SELECT auth_has_module_permission('orphan_objects', 'can_view')));

CREATE POLICY "orphan_objects_registry_update" ON public.orphan_objects_registry
  FOR UPDATE TO authenticated
  USING ((SELECT auth_can_edit_any(ARRAY['orphan_objects'])))
  WITH CHECK ((SELECT auth_can_edit_any(ARRAY['orphan_objects'])));

REVOKE ALL ON public.orphan_objects_registry FROM anon;
GRANT SELECT, UPDATE ON public.orphan_objects_registry TO authenticated;
GRANT ALL ON public.orphan_objects_registry TO service_role;

-- Seed: casos ya confirmados en sesiones pasadas (verificado de nuevo antes
-- de sembrar, no copiado ciego de las notas viejas — ver detalle por fila).
INSERT INTO public.orphan_objects_registry (kind, ref, title, status, resolved_at, notes) VALUES
(
  'component', 'src/components/SalyChatOverlay.jsx (histórico)', 'SalyChatOverlay (chat de Saly)',
  'resolved', now(),
  'Ya eliminado del repo — confirmado 2026-07-16, el archivo ya no existe, solo queda mencionado en el changelog de src/version.js.'
),
(
  'component', 'src/views/pedidos/tabpedidos/StageAnims.jsx', 'StageAnim (animación de stage en Pedidos)',
  'candidate', null,
  'Importado en TabPedidos.jsx:35 pero nunca usado en el JSX del archivo — import muerto. Extraído mecánicamente en Bloque 6.C, sin caller desde entonces. Verificado 2026-07-16.'
),
(
  'component', 'src/views/pedidos/tabpedidos/EmpChip.jsx', 'EmpChip (extraído de TabPedidos, Bloque 6.C)',
  'candidate', null,
  'Importado en TabPedidos.jsx:36 pero nunca usado en el JSX del archivo. No confundir con el EmpChip local de RecepcionModal.jsx (componente distinto, mismo nombre). Verificado 2026-07-16.'
),
(
  'component', 'src/views/pedidos/tabpedidos/StagePill.jsx', 'StagePill (extraído de TabPedidos, Bloque 6.C)',
  'candidate', null,
  'Importado en TabPedidos.jsx:37 pero nunca usado en el JSX del archivo. No confundir con BranchStagePill local de TabEnCurso.jsx (componente distinto). Verificado 2026-07-16.'
),
(
  'component', 'src/views/pedidos/RutaEnCursoCard.jsx', 'RutaEnCursoCard',
  'candidate', null,
  'Sin ningún import/uso en todo src/ (confirmado por grep 2026-07-16). El changelog v2.2.341 dice "eliminar RutaEnCursoCard" pero el archivo nunca se borró del repo.'
),
(
  'component', 'src/components/ShiftExceptionModal.jsx', 'ShiftExceptionModal',
  'candidate', null,
  'Renderizado condicionalmente en EmployeeDetailView.jsx vía el estado showExceptionModal, pero setShowExceptionModal(true) nunca se llama en ningún lugar del archivo — el modal está declarado pero no hay ningún botón/acción que lo dispare. Verificado 2026-07-16.'
),
(
  'modal', 'src/components/forms/FormAiSchedulerPreview.jsx (tipo "aiSchedulerPreview" en UnifiedModal.jsx)', 'FormAiSchedulerPreview',
  'candidate', null,
  'UnifiedModal.jsx maneja el tipo de modal "aiSchedulerPreview" (título, tamaño, footer) pero ningún openModal(...) en todo el repo lo invoca. Verificado 2026-07-16.'
),
(
  'edge_function', 'supabase/functions/sync-erp-minmax', 'sync-erp-minmax',
  'candidate', null,
  'Escribe a la tabla erp_minmax, eliminada en v2.2.209 (migración remove_erp_minmax_table) — la función fallaría con "relation does not exist" si se invocara. Sin cron activo en cron.job. Encontrado 2026-07-16 durante Fase 0 de Bloque 7B (se había editado por error creyendo que estaba viva; se revirtió antes de redesplegar).'
);

-- Acceso: mismo criterio ya establecido en 7B.3 (rol real "Supervisor/a de
-- Ventas", primario de Edwin Nuñez, hace de viewer técnico de "Sistema").
INSERT INTO public.role_permissions (role_id, module_key, can_view, can_edit)
VALUES (13, 'orphan_objects', true, true)
ON CONFLICT DO NOTHING;

-- Acceso: mismo criterio ya establecido en 7B.3 (rol real "Supervisor/a de
-- Ventas", primario de Edwin Nuñez, hace de viewer técnico de "Sistema").
INSERT INTO public.role_permissions (role_id, module_key, can_view, can_edit)
VALUES (13, 'orphan_objects', true, true)
ON CONFLICT DO NOTHING;
