SET lock_timeout = '5s';

CREATE TABLE public.sync_alert_log (
  id          bigint generated by default as identity primary key,
  domain      text not null,
  scope_key   text not null,
  alert_key   text not null,
  sent_at     timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  UNIQUE (domain, scope_key, alert_key)
);

ALTER TABLE public.sync_alert_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sync_alert_log_select" ON public.sync_alert_log
  FOR SELECT TO authenticated
  USING ((SELECT auth_has_module_permission('sync_health', 'can_view')));

REVOKE ALL ON public.sync_alert_log FROM anon;
GRANT SELECT ON public.sync_alert_log TO authenticated, service_role;
GRANT INSERT ON public.sync_alert_log TO service_role;
