-- Bloque 7B, Fase 0: infraestructura común de sync logs.
-- products/minmax/backup no tenían ninguna tabla de log de fallos hoy (solo
-- console.error o error en la respuesta HTTP, nada persistido). Estas 3 tablas
-- + la vista v_sync_health son el prerrequisito de 7B.1 (alertas) y 7B.3
-- (dashboard). Mismo esquema base que purchase_sync_log (patrón ya probado).

SET lock_timeout = '5s';

CREATE TABLE public.products_sync_log (
  id                bigint generated by default as identity primary key,
  checked_at        timestamptz not null default now(),
  success           boolean not null,
  error_msg         text,
  products_written  integer,
  product_changes   integer,
  created_at        timestamptz not null default now()
);

CREATE TABLE public.minmax_sync_log (
  id                bigint generated by default as identity primary key,
  source            text not null check (source in ('sync-erp-minmax','auto-calculate-minmax')),
  erp_sucursal_id   smallint,
  checked_at        timestamptz not null default now(),
  success           boolean not null,
  error_msg         text,
  items_count       integer,
  created_at        timestamptz not null default now()
);

CREATE TABLE public.backup_sync_log (
  id                bigint generated by default as identity primary key,
  checked_at        timestamptz not null default now(),
  success           boolean not null,
  error_msg         text,
  tables_ok         integer,
  tables_failed     integer,
  total_kb          integer,
  created_at        timestamptz not null default now()
);

CREATE INDEX idx_products_sync_log_checked_at ON public.products_sync_log (checked_at DESC);
CREATE INDEX idx_minmax_sync_log_checked_at   ON public.minmax_sync_log (checked_at DESC);
CREATE INDEX idx_backup_sync_log_checked_at   ON public.backup_sync_log (checked_at DESC);

ALTER TABLE public.products_sync_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minmax_sync_log   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backup_sync_log   ENABLE ROW LEVEL SECURITY;

-- Gate nuevo dedicado 'sync_health' (lo registra 7B.3 en role_permissions;
-- hasta entonces nadie sin ese permiso ve filas, SUPERADMIN sigue viendo todo
-- vía el bypass ya establecido de auth_has_module_permission).
CREATE POLICY "products_sync_log_select" ON public.products_sync_log
  FOR SELECT TO authenticated
  USING ((SELECT auth_has_module_permission('sync_health', 'can_view')));

CREATE POLICY "minmax_sync_log_select" ON public.minmax_sync_log
  FOR SELECT TO authenticated
  USING ((SELECT auth_has_module_permission('sync_health', 'can_view')));

CREATE POLICY "backup_sync_log_select" ON public.backup_sync_log
  FOR SELECT TO authenticated
  USING ((SELECT auth_has_module_permission('sync_health', 'can_view')));

REVOKE ALL ON public.products_sync_log FROM anon;
REVOKE ALL ON public.minmax_sync_log   FROM anon;
REVOKE ALL ON public.backup_sync_log   FROM anon;
GRANT SELECT ON public.products_sync_log TO authenticated, service_role;
GRANT SELECT ON public.minmax_sync_log   TO authenticated, service_role;
GRANT SELECT ON public.backup_sync_log   TO authenticated, service_role;
GRANT INSERT ON public.products_sync_log TO service_role;
GRANT INSERT ON public.minmax_sync_log   TO service_role;
GRANT INSERT ON public.backup_sync_log   TO service_role;

-- Vista unificada, solo lectura, security_invoker (regla #5 CLAUDE.md) — cada
-- fila respeta la RLS de su tabla origen, así que un rol solo ve los dominios
-- para los que ya tiene permiso (dte_sync/compras/sync_health respectivamente).
-- Tipos normalizados explícitamente (branch_id→bigint, erp_sucursal_id→integer)
-- porque sync_log.branch_id es bigint y purchase_sync_log.branch_id es integer.
CREATE VIEW public.v_sync_health WITH (security_invoker = true) AS
  SELECT 'dte'::text AS domain, NULL::text AS source,
    branch_id::bigint AS branch_id, NULL::integer AS erp_sucursal_id,
    ran_at AS checked_at, success, error_msg
  FROM public.sync_log
  UNION ALL
  SELECT 'inventory', NULL,
    NULL::bigint, erp_sucursal_id::integer,
    synced_at, success, error_msg
  FROM public.inventory_sync_log
  UNION ALL
  SELECT 'purchases', NULL,
    branch_id::bigint, erp_sucursal_id::integer,
    synced_at, success, error_msg
  FROM public.purchase_sync_log
  UNION ALL
  SELECT 'products', NULL,
    NULL::bigint, NULL::integer,
    checked_at, success, error_msg
  FROM public.products_sync_log
  UNION ALL
  SELECT 'minmax', source,
    NULL::bigint, erp_sucursal_id::integer,
    checked_at, success, error_msg
  FROM public.minmax_sync_log
  UNION ALL
  SELECT 'backup', NULL,
    NULL::bigint, NULL::integer,
    checked_at, success, error_msg
  FROM public.backup_sync_log;
