-- Bolsas de efectivo — la bolsa nace sola, y el circuito llega hasta el conteo.
--
-- Dos pedidos del usuario (2026-08-15):
--
--   1. «al confirmar el corte, se debe guardar la bolsa automaticamente».
--      La version anterior lo hacia en dos pasos a proposito —meter el dinero
--      es un acto fisico— y el usuario decidio lo contrario. Queda anotado el
--      efecto: el registro afirma que la bolsa existe apenas se firma el corte,
--      asi que la correccion pasa a ser `anular_bolsa`, que exige motivo y
--      queda en la bitacora. A cambio, el invariante se cumple solo: todo corte
--      confirmado tiene su bolsa.
--
--   2. La vista donde vive el proceso entero, incluido el conteo en
--      administracion: ENTREGADA -> RECIBIDA -> CONTADA, y la resolucion de la
--      diferencia.
--
-- Probada en el branch de staging con una transaccion revertida: sin bolsa
-- mientras el corte esta PENDIENTE, S3-1001 por 666.65 al confirmar el primero,
-- S3-1002 por 511.25 al confirmar el segundo (suma 1177.90 = lo declarado en el
-- ultimo corte, que es el invariante), y reconfirmar no duplica.

SET lock_timeout = '5s';

ALTER TABLE public.bolsas
    ADD COLUMN IF NOT EXISTS entregada_por uuid REFERENCES public.employees(id),
    ADD COLUMN IF NOT EXISTS entregada_at  timestamptz,
    ADD COLUMN IF NOT EXISTS recibida_por  uuid REFERENCES public.employees(id),
    ADD COLUMN IF NOT EXISTS recibida_at   timestamptz,
    -- Lo que conto administracion. NO se edita nunca: si al reponer se
    -- sobreescribiera, el faltante desapareceria de la historia y con el la
    -- razon por la que alguien puso dinero de su bolsillo.
    ADD COLUMN IF NOT EXISTS contado       numeric(12,2),
    ADD COLUMN IF NOT EXISTS contado_por   uuid REFERENCES public.employees(id),
    ADD COLUMN IF NOT EXISTS contado_at    timestamptz,
    ADD COLUMN IF NOT EXISTS dif_via       text,
    ADD COLUMN IF NOT EXISTS dif_causa     text,
    ADD COLUMN IF NOT EXISTS dif_por       uuid REFERENCES public.employees(id),
    ADD COLUMN IF NOT EXISTS dif_at        timestamptz;

DO $$ BEGIN
    ALTER TABLE public.bolsas ADD CONSTRAINT bolsas_dif_via_valida
        CHECK (dif_via IS NULL OR dif_via IN ('REPONE','RETIRA','JUSTIFICA'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS bolsas_estado_fecha ON public.bolsas(estado, fecha DESC);

-- ── La bitacora ─────────────────────────────────────────────────────────────
-- Calcada de `cortes_caja_eventos`, y por el mismo motivo: las columnas de la
-- bolsa guardan solo la ULTIMA decision.
CREATE TABLE IF NOT EXISTS public.bolsas_eventos (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bolsa_id       bigint      NOT NULL REFERENCES public.bolsas(id) ON DELETE CASCADE,
    accion         text        NOT NULL,
    estado_antes   text,
    estado_despues text,
    motivo         text,
    nota           text,
    monto          numeric(12,2),
    employee_id    uuid        REFERENCES public.employees(id),
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bolsas_eventos_bolsa ON public.bolsas_eventos(bolsa_id, created_at DESC);
CREATE INDEX IF NOT EXISTS bolsas_eventos_employee ON public.bolsas_eventos(employee_id);

ALTER TABLE public.bolsas_eventos ENABLE ROW LEVEL SECURITY;

-- Cuelga de la policy de `bolsas`: quien ve la bolsa ve su historia, y quien no,
-- no. Una sola definicion de alcance para las dos tablas.
DROP POLICY IF EXISTS bolsas_eventos_select ON public.bolsas_eventos;
CREATE POLICY bolsas_eventos_select ON public.bolsas_eventos
    FOR SELECT TO authenticated
    USING (EXISTS (SELECT 1 FROM public.bolsas b WHERE b.id = bolsas_eventos.bolsa_id));

DROP POLICY IF EXISTS bloqueo_global ON public.bolsas_eventos;
CREATE POLICY bloqueo_global ON public.bolsas_eventos
    AS RESTRICTIVE FOR ALL TO public
    USING ((SELECT auth_no_bloqueado()));

REVOKE ALL ON public.bolsas_eventos FROM anon;
GRANT SELECT ON public.bolsas_eventos TO authenticated;
GRANT ALL ON public.bolsas_eventos TO service_role;

-- ── Lo que DEBE haber adentro ───────────────────────────────────────────────
-- Hoy es el monto guardado y nada mas, porque todavia no existen las salidas.
-- Existe igual, y separada, para que el dia que se sumen los vales haya UN solo
-- lugar donde cambiarlo: quien cuenta y quien imprime la etiqueta tienen que
-- leer el mismo numero.
CREATE OR REPLACE FUNCTION public.bolsa_saldo(p_bolsa_id bigint)
RETURNS numeric
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT b.monto_inicial FROM public.bolsas b WHERE b.id = p_bolsa_id;
$$;

REVOKE EXECUTE ON FUNCTION public.bolsa_saldo(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.bolsa_saldo(bigint) TO authenticated, service_role;

-- ── A quien se le avisa ─────────────────────────────────────────────────────
-- `destinatarios_de_cortes` era esta misma consulta con el modulo escrito
-- adentro. Se generaliza en vez de copiarla: dos versiones de «a quien de esta
-- sala le importa» se desincronizan, y desincronizadas significan que a alguien
-- deja de llegarle un aviso de dinero.
CREATE OR REPLACE FUNCTION public.destinatarios_de_modulo(p_branch_id integer, p_module_key text)
RETURNS uuid[]
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    -- Los de la sala que tienen el modulo. `notify_branch` avisaria a TODOS los
    -- de la sucursal, y a quien no lo tiene el aviso lo manda a una pantalla que
    -- no puede abrir.
    SELECT array_agg(DISTINCT e.id)
      FROM public.employees e
      JOIN public.role_permissions rp
        ON rp.role_id = e.role_id
       AND rp.module_key = p_module_key
     WHERE e.branch_id = p_branch_id
       AND e.status = 'ACTIVO'
       AND (rp.can_view OR rp.can_edit);
$$;

REVOKE EXECUTE ON FUNCTION public.destinatarios_de_modulo(integer, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.destinatarios_de_modulo(integer, text) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.destinatarios_de_cortes(p_branch_id integer)
RETURNS uuid[]
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT public.destinatarios_de_modulo(p_branch_id, 'cortes_caja');
$$;

-- ── El folio, en un solo sitio ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nuevo_folio_de_bolsa(p_branch_id bigint)
RETURNS text
LANGUAGE sql VOLATILE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT upper(btrim(coalesce((SELECT b.codigo FROM public.branches b WHERE b.id = p_branch_id), 'B')))
           || '-' || nextval('public.bolsas_folio_seq');
$$;

REVOKE EXECUTE ON FUNCTION public.nuevo_folio_de_bolsa(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.nuevo_folio_de_bolsa(bigint) TO authenticated, service_role;

-- ── La bolsa nace al confirmar el corte ─────────────────────────────────────
-- El disparador va sobre el UPDATE y NO sobre el INSERT: el INSERT es la
-- captura del cron, y un error ahi dejaria de entrar los cortes de TODAS las
-- salas (es la leccion de `trg_notificar_corte_de_caja`).
--
-- NUNCA aborta la confirmacion por no tener nada que guardar: si el monto
-- sugerido es cero o negativo —un corte rehecho, o uno cuyo efectivo ya esta
-- embolsado— simplemente no crea la bolsa.
CREATE OR REPLACE FUNCTION public.crear_bolsa_al_confirmar()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_monto numeric;
    v_bolsa public.bolsas;
BEGIN
    IF NEW.tipo <> 'C' THEN RETURN NEW; END IF;

    IF EXISTS (SELECT 1 FROM public.bolsas b
                WHERE b.corte_id = NEW.id AND b.estado <> 'ANULADA') THEN
        RETURN NEW;
    END IF;

    v_monto := public.bolsa_sugerida(NEW.id);
    IF v_monto IS NULL OR v_monto <= 0 THEN RETURN NEW; END IF;

    INSERT INTO public.bolsas
        (folio, branch_id, corte_id, origen, monto_inicial, fecha, hora, caja, cerrada_por)
    VALUES
        (public.nuevo_folio_de_bolsa(NEW.branch_id),
         NEW.branch_id, NEW.id, 'CORTE', v_monto,
         NEW.fecha, NEW.hora, NEW.empleado_texto, NEW.resuelto_por)
    RETURNING * INTO v_bolsa;

    INSERT INTO public.bolsas_eventos (bolsa_id, accion, estado_despues, monto, employee_id, nota)
    VALUES (v_bolsa.id, 'CREAR', 'ABIERTA', v_monto, NEW.resuelto_por,
            'Nacio al confirmarse el corte.');

    RETURN NEW;
END;
$$;

-- Separado del CREATE FUNCTION a proposito: es el patron que ya se uso para el
-- aviso de cortes, para poder desenchufar el disparador sin tocar la funcion.
DROP TRIGGER IF EXISTS trg_bolsa_al_confirmar ON public.cortes_caja;
CREATE TRIGGER trg_bolsa_al_confirmar
    AFTER UPDATE ON public.cortes_caja
    FOR EACH ROW
    WHEN (NEW.estado = 'CONFIRMADO' AND OLD.estado IS DISTINCT FROM 'CONFIRMADO')
    EXECUTE FUNCTION public.crear_bolsa_al_confirmar();

-- ── Entregar: la bolsa sale de la sala ──────────────────────────────────────
CREATE OR REPLACE FUNCTION public.entregar_bolsas(p_ids bigint[])
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_yo    uuid := (SELECT auth_employee_id());
    v_scope text := (SELECT auth_module_scope('bolsas'));
    v_mia   bigint := (SELECT auth_employee_branch_id());
    v_n     integer := 0;
    r       record;
BEGIN
    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas'])) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    FOR r IN SELECT * FROM public.bolsas WHERE id = ANY(p_ids) FOR UPDATE LOOP
        IF v_scope IS DISTINCT FROM 'ALL' AND r.branch_id IS DISTINCT FROM v_mia THEN
            RAISE EXCEPTION 'FORBIDDEN';
        END IF;
        IF r.estado <> 'ABIERTA' THEN
            RAISE EXCEPTION 'La bolsa % ya salio de la sala.', r.folio;
        END IF;

        UPDATE public.bolsas
           SET estado = 'ENTREGADA', entregada_por = v_yo, entregada_at = now(), updated_at = now()
         WHERE id = r.id;

        INSERT INTO public.bolsas_eventos (bolsa_id, accion, estado_antes, estado_despues, monto, employee_id)
        VALUES (r.id, 'ENTREGAR', r.estado, 'ENTREGADA', r.monto_inicial, v_yo);

        v_n := v_n + 1;
    END LOOP;

    RETURN v_n;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.entregar_bolsas(bigint[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.entregar_bolsas(bigint[]) TO authenticated, service_role;

-- ── Recibir: administracion acusa recibo, sin contar ────────────────────────
-- Cuenta BOLSAS, no dinero: es el paso rapido de cuando llega la valija, y el
-- conteo puede ser al otro dia.
--
-- QUIEN ENTREGA NO PUEDE RECIBIR. Dos confirmaciones firmadas por la misma
-- persona no son un control, son dos clics — y la regla va en el servidor.
CREATE OR REPLACE FUNCTION public.recibir_bolsas(p_ids bigint[])
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_yo uuid := (SELECT auth_employee_id());
    v_n  integer := 0;
    r    record;
BEGIN
    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas_conteo'])) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    FOR r IN SELECT * FROM public.bolsas WHERE id = ANY(p_ids) FOR UPDATE LOOP
        IF r.estado <> 'ENTREGADA' THEN
            RAISE EXCEPTION 'La bolsa % no esta esperando recepcion.', r.folio;
        END IF;
        IF r.entregada_por IS NOT NULL AND r.entregada_por = v_yo THEN
            RAISE EXCEPTION 'La bolsa % la entregaste vos: la recepcion la firma otra persona.', r.folio;
        END IF;

        UPDATE public.bolsas
           SET estado = 'RECIBIDA', recibida_por = v_yo, recibida_at = now(), updated_at = now()
         WHERE id = r.id;

        INSERT INTO public.bolsas_eventos (bolsa_id, accion, estado_antes, estado_despues, monto, employee_id)
        VALUES (r.id, 'RECIBIR', r.estado, 'RECIBIDA', r.monto_inicial, v_yo);

        v_n := v_n + 1;
    END LOOP;

    RETURN v_n;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.recibir_bolsas(bigint[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.recibir_bolsas(bigint[]) TO authenticated, service_role;

-- ── Contar: el dinero sobre la mesa ─────────────────────────────────────────
-- `p_esperado` es lo que decia la pantalla; el servidor calcula el suyo y
-- rechaza si no coinciden. Es la cifra contra la que despues se le reclama a
-- alguien: no la puede elegir el navegador.
--
-- Cuando no cuadra, le avisa a la sala. ACA EL MONTO SI VA EN EL AVISO — a
-- diferencia del aviso de un corte nuevo, donde la cifra es provisional: esta
-- es un conteo firmado y ya no cambia.
CREATE OR REPLACE FUNCTION public.contar_bolsa(
    p_id       bigint,
    p_contado  numeric,
    p_esperado numeric
)
RETURNS public.bolsas
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_bolsa  public.bolsas;
    v_saldo  numeric;
    v_dif    numeric;
    v_yo     uuid := (SELECT auth_employee_id());
    v_sala   text;
BEGIN
    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas_conteo'])) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    IF p_contado IS NULL OR p_contado < 0 THEN
        RAISE EXCEPTION 'Hay que escribir cuanto se conto.';
    END IF;

    SELECT * INTO v_bolsa FROM public.bolsas WHERE id = p_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'La bolsa no existe.'; END IF;

    IF v_bolsa.estado <> 'RECIBIDA' THEN
        RAISE EXCEPTION 'La bolsa % no esta lista para contar.', v_bolsa.folio;
    END IF;

    v_saldo := public.bolsa_saldo(p_id);
    IF round(coalesce(p_esperado, -1), 2) <> round(v_saldo, 2) THEN
        RAISE EXCEPTION 'Lo que debe haber cambio mientras estabas en la pantalla: ahora son % y en pantalla decia %.',
            to_char(v_saldo, 'FM999999990.00'),
            to_char(round(coalesce(p_esperado, 0), 2), 'FM999999990.00');
    END IF;

    v_dif := round(p_contado - v_saldo, 2);

    UPDATE public.bolsas
       SET estado      = 'CONTADA',
           contado     = round(p_contado, 2),
           contado_por = v_yo,
           contado_at  = now(),
           updated_at  = now()
     WHERE id = p_id
     RETURNING * INTO v_bolsa;

    INSERT INTO public.bolsas_eventos (bolsa_id, accion, estado_antes, estado_despues, monto, employee_id, nota)
    VALUES (p_id, 'CONTAR', 'RECIBIDA', 'CONTADA', v_dif, v_yo,
            CASE WHEN abs(v_dif) < 0.01 THEN 'Cuadro.' ELSE 'No cuadro.' END);

    IF abs(v_dif) >= 0.01 THEN
        SELECT name INTO v_sala FROM public.branches WHERE id = v_bolsa.branch_id;
        PERFORM public.notify_employees(
            public.destinatarios_de_modulo(v_bolsa.branch_id::integer, 'bolsas'),
            'bolsa_no_cuadra',
            CASE WHEN v_dif < 0 THEN 'Falto dinero en una bolsa' ELSE 'Sobro dinero en una bolsa' END,
            format('%s - bolsa %s del corte del %s. Debia haber %s y se contaron %s.',
                   coalesce(v_sala, 'Sala'), v_bolsa.folio,
                   to_char(v_bolsa.fecha, 'DD/MM/YYYY'),
                   to_char(v_saldo, 'FM999999990.00'),
                   to_char(round(p_contado, 2), 'FM999999990.00')),
            '/cortes',
            jsonb_build_object('bolsa_id', p_id, 'folio', v_bolsa.folio, 'diferencia', v_dif),
            true,
            v_bolsa.branch_id::integer
        );
    END IF;

    RETURN v_bolsa;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.contar_bolsa(bigint, numeric, numeric) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.contar_bolsa(bigint, numeric, numeric) TO authenticated, service_role;

-- ── Resolver la diferencia ──────────────────────────────────────────────────
-- Las mismas tres vias que en los cortes: REPONE (entra dinero), RETIRA (sale)
-- y JUSTIFICA (no mueve nada, aparecio la explicacion).
--
-- LO CONTADO NO SE TOCA. Quedan los dos numeros para siempre: lo que se conto y
-- lo que se hizo.
CREATE OR REPLACE FUNCTION public.resolver_diferencia_bolsa(
    p_id    bigint,
    p_via   text,
    p_causa text
)
RETURNS public.bolsas
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_bolsa public.bolsas;
    v_yo    uuid := (SELECT auth_employee_id());
    v_scope text := (SELECT auth_module_scope('bolsas'));
BEGIN
    -- La resuelve administracion (que cuenta) o la propia sala (que repone).
    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas_conteo','bolsas'])) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    IF p_via NOT IN ('REPONE','RETIRA','JUSTIFICA') THEN
        RAISE EXCEPTION 'Via invalida: %', p_via;
    END IF;
    IF p_causa IS NULL OR btrim(p_causa) = '' THEN
        RAISE EXCEPTION 'Resolver una diferencia exige decir por que.';
    END IF;

    SELECT * INTO v_bolsa FROM public.bolsas WHERE id = p_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'La bolsa no existe.'; END IF;

    IF v_bolsa.estado <> 'CONTADA' OR v_bolsa.contado IS NULL THEN
        RAISE EXCEPTION 'Esta bolsa todavia no se conto.';
    END IF;
    IF abs(round(v_bolsa.contado - public.bolsa_saldo(p_id), 2)) < 0.01 THEN
        RAISE EXCEPTION 'Esta bolsa cuadro: no hay nada que resolver.';
    END IF;

    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas_conteo']))
       AND v_scope IS DISTINCT FROM 'ALL'
       AND v_bolsa.branch_id IS DISTINCT FROM (SELECT auth_employee_branch_id()) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    UPDATE public.bolsas
       SET dif_via = p_via, dif_causa = btrim(p_causa), dif_por = v_yo, dif_at = now(),
           updated_at = now()
     WHERE id = p_id
     RETURNING * INTO v_bolsa;

    INSERT INTO public.bolsas_eventos (bolsa_id, accion, estado_antes, estado_despues, motivo, monto, employee_id)
    VALUES (p_id, 'RESOLVER', 'CONTADA', 'CONTADA', btrim(p_causa),
            round(v_bolsa.contado - public.bolsa_saldo(p_id), 2), v_yo);

    RETURN v_bolsa;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.resolver_diferencia_bolsa(bigint, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.resolver_diferencia_bolsa(bigint, text, text) TO authenticated, service_role;

-- ── La bitacora de una bolsa ────────────────────────────────────────────────
-- Con el nombre de quien hizo cada cosa. NO va contra `employees_safe`: su
-- policy esconde a los superusuarios de todos menos de si mismos, y quien
-- cuenta el dinero suele serlo — la pantalla diria «sin registrar quien» sobre
-- una decision que si tiene autor.
CREATE OR REPLACE FUNCTION public.get_bolsa_eventos(p_bolsa_id bigint)
RETURNS TABLE (
    id bigint, accion text, estado_antes text, estado_despues text,
    motivo text, nota text, monto numeric, created_at timestamptz,
    employee_id uuid, nombre text, photo_url text
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT ev.id, ev.accion, ev.estado_antes, ev.estado_despues,
           ev.motivo, ev.nota, ev.monto, ev.created_at,
           ev.employee_id, e.name, e.photo_url
      FROM public.bolsas_eventos ev
      LEFT JOIN public.employees e ON e.id = ev.employee_id
     WHERE ev.bolsa_id = p_bolsa_id
       AND (SELECT auth_has_module_permission('bolsas','can_view'))
     ORDER BY ev.created_at DESC, ev.id DESC;
$$;

REVOKE EXECUTE ON FUNCTION public.get_bolsa_eventos(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_bolsa_eventos(bigint) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.get_bolsas_personas(p_ids uuid[])
RETURNS TABLE (id uuid, name text, photo_url text)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT e.id, e.name, e.photo_url
      FROM public.employees e
     WHERE e.id = ANY(p_ids)
       AND (SELECT auth_has_module_permission('bolsas','can_view'));
$$;

REVOKE EXECUTE ON FUNCTION public.get_bolsas_personas(uuid[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_bolsas_personas(uuid[]) TO authenticated, service_role;

-- ── Permisos ────────────────────────────────────────────────────────────────
-- `bolsas_conteo` es un modulo APARTE de `bolsas` porque son dos publicos: la
-- sala entrega, administracion recibe y cuenta. Con un solo permiso, darle a la
-- sala lo suyo le daria tambien el poder de dar por buena su propia bolsa.
--
-- Se siembra a los cargos que hoy ven TODAS las salas en cortes de caja: son
-- los de administracion. Los de sala (scope BRANCH) quedan fuera a proposito.
INSERT INTO public.role_permissions (role_id, module_key, can_view, can_edit, can_approve, scope)
SELECT rp.role_id, 'bolsas_conteo', true, rp.can_edit, false, 'ALL'
  FROM public.role_permissions rp
 WHERE rp.module_key = 'cortes_caja' AND rp.scope = 'ALL'
ON CONFLICT (role_id, module_key) DO NOTHING;
