SET lock_timeout = '5s';

-- ══════════════════════════════════════════════════════════════════════════
-- El espejo del ERP destruía las ediciones hechas desde el portal.
--
-- `aplicar_espejo_erp` reescribía las 15 columnas sin condición. Comprobado en
-- vivo el 2026-08-01 16:01 UTC: de las 2 fichas que tenían edición del portal,
-- pisó las 2 (cliente 16164, teléfono borrado a mano -> volvió '1111-1111';
-- cliente 14529, distrito 'Chalatenango' -> 'CHALATENANGO'). Y como
-- `customers` no tiene ningún trigger, las 826 filas reescritas no dejaron ni
-- una línea en `customers_changelog`: la bitácora seguía diciendo que la
-- corrección de la persona estaba vigente.
--
-- Segundo defecto, más silencioso: el cliente omite los campos vacíos, así que
-- llegaban como NULL y el UPDATE los escribía. De las 1,016 fichas del último
-- espejo, 98% venían sin correo y 99% sin NIT/NRC/teléfono 2/giro — o sea que
-- cualquier correo cargado desde el portal se borraba en la corrida siguiente.
--
-- REGLA ACORDADA: el ERP es la autoridad. Lo que se protege NO es "el portal
-- gana", sino el tramo en que una edición del portal todavía no tuvo chance de
-- llegar al ERP. En cuanto la Fase 2 la empuje y marque `erp_synced_at`, la
-- protección se levanta sola y el ERP vuelve a mandar para siempre.
--
-- Por qué no alcanzaba COALESCE(NULLIF(c.campo,''), e.campo): dejaría al portal
-- ganando siempre que tenga algo cargado, y con eso una corrección hecha en el
-- ERP no llegaría nunca. Hoy hay 890 clientes con distrito puesto por el espejo
-- —dos de ellos anotados como probablemente mal (erp 3461 y 1672)— y solo 3
-- clientes en todo el portal tienen alguna edición. COALESCE congelaría 890
-- para proteger 3.
-- ══════════════════════════════════════════════════════════════════════════

-- ── Dónde queda anotado que el ERP le ganó a una edición del portal ────────
CREATE TABLE IF NOT EXISTS public.espejo_conflictos (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   bigint NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    changelog_id  bigint REFERENCES public.customers_changelog(id) ON DELETE SET NULL,
    campo         text   NOT NULL,
    valor_base    text,          -- lo que el ERP tenía cuando la persona editó
    valor_portal  text,          -- lo que la persona quiso dejar
    valor_erp     text,          -- lo que el ERP impuso
    created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.espejo_conflictos IS
  'Ediciones del portal que el espejo del ERP descartó porque el ERP también '
  'había cambiado ese campo. Hoy el ERP es la autoridad, así que gana él — pero '
  'no en silencio. La Fase 2 NO debe empujar una entrada de customers_changelog '
  'que figure acá: el ERP ya se movió más allá de ese valor.';

CREATE INDEX IF NOT EXISTS espejo_conflictos_customer_idx
    ON public.espejo_conflictos(customer_id);
CREATE INDEX IF NOT EXISTS espejo_conflictos_changelog_idx
    ON public.espejo_conflictos(changelog_id);

ALTER TABLE public.espejo_conflictos ENABLE ROW LEVEL SECURITY;

-- Solo lectura para la app. Escribe únicamente el RPC, que es SECURITY DEFINER
-- y por eso no necesita policy de INSERT (y no se le pone: un WITH CHECK (true)
-- dejaría fabricar filas de bitácora a cualquier autenticado).
DROP POLICY IF EXISTS espejo_conflictos_select ON public.espejo_conflictos;
CREATE POLICY espejo_conflictos_select ON public.espejo_conflictos
    FOR SELECT TO authenticated USING (true);

REVOKE ALL ON public.espejo_conflictos FROM anon;
GRANT SELECT ON public.espejo_conflictos TO authenticated;


-- ── La decisión, campo por campo ──────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.espejo_valor(
        p_erp text, p_actual text, p_prot jsonb, p_campo text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, extensions
AS $$
  SELECT CASE
    -- 1. El ERP no manda el dato. NO es lo mismo que "el ERP dice vacío": el
    --    cliente omite los campos nulos, así que acá NULL significa "sin
    --    información", y sin información no se borra nada.
    WHEN p_erp IS NULL THEN p_actual

    -- 2. No hay edición del portal pendiente de empujar: manda el ERP.
    WHEN p_prot -> p_campo IS NULL THEN p_erp

    -- 3. Hay edición pendiente y el ERP sigue con el valor que tenía cuando la
    --    persona editó: se respeta la edición hasta que la Fase 2 la empuje.
    WHEN p_erp IS NOT DISTINCT FROM (p_prot -> p_campo ->> 'base') THEN p_actual

    -- 4. Hay edición pendiente Y el ERP también se movió. Gana el ERP —hoy es
    --    la autoridad— y el descarte queda en espejo_conflictos.
    ELSE p_erp
  END;
$$;

REVOKE EXECUTE ON FUNCTION public.espejo_valor(text, text, jsonb, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.espejo_valor(text, text, jsonb, text) TO authenticated, service_role;


-- ── El espejo ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.aplicar_espejo_erp(p_filas json)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $function$
DECLARE
  v_resultado json;
BEGIN
  WITH filas AS (
    SELECT * FROM json_to_recordset(p_filas) AS x(
        match_name    text, erp_id text, nit text, dui text, nrc text,
        phone         text, telefono2 text, email text, direccion text,
        pasaporte     text, departamento text, municipio text, distrito text,
        categoria     text, giro text, retencion_pct smallint)
  ), conteo AS (
    SELECT match_name, count(*) AS n FROM filas GROUP BY 1
  ), unicas AS (
    SELECT f.* FROM filas f JOIN conteo c USING (match_name) WHERE c.n = 1

  -- Ediciones del portal que todavía no llegaron al ERP. `valor_base` es lo que
  -- el campo tenía ANTES de que la persona lo tocara —o sea lo que el ERP le
  -- había puesto—, y es la referencia para saber si el ERP se movió después.
  ), pendientes AS (
    SELECT customer_id, campo,
           (array_agg(valor_anterior ORDER BY changed_at,      id     ))[1] AS valor_base,
           (array_agg(valor_nuevo    ORDER BY changed_at DESC, id DESC))[1] AS valor_portal,
           (array_agg(id             ORDER BY changed_at DESC, id DESC))[1] AS changelog_id
    FROM public.customers_changelog
    WHERE erp_synced_at IS NULL
    GROUP BY customer_id, campo
  ), prot AS (
    SELECT customer_id,
           jsonb_object_agg(campo, jsonb_build_object(
               'base', valor_base, 'portal', valor_portal)) AS campos
    FROM pendientes GROUP BY customer_id
  ), objetivo AS (
    SELECT c.id AS customer_id, e.*, coalesce(p.campos, '{}'::jsonb) AS prot
    FROM unicas e
    JOIN public.customers c ON c.search_name = e.match_name
    LEFT JOIN prot p ON p.customer_id = c.id

  -- El mismo valor entrante, en formato (campo, valor), para poder cruzarlo
  -- contra `pendientes` sin repetir un CASE de 14 ramas.
  ), entrantes AS (
    SELECT o.customer_id, v.campo, v.valor
    FROM objetivo o
    CROSS JOIN LATERAL (VALUES
        ('nit', o.nit), ('dui', o.dui), ('nrc', o.nrc), ('phone', o.phone),
        ('telefono2', o.telefono2), ('email', o.email),
        ('direccion', o.direccion), ('pasaporte', o.pasaporte),
        ('departamento', o.departamento), ('municipio', o.municipio),
        ('distrito', o.distrito), ('categoria', o.categoria),
        ('giro', o.giro), ('retencion_pct', o.retencion_pct::text)
    ) AS v(campo, valor)
  ), conflictos AS (
    SELECT en.customer_id, pe.changelog_id, en.campo,
           pe.valor_base, pe.valor_portal, en.valor AS valor_erp
    FROM entrantes en
    JOIN pendientes pe ON pe.customer_id = en.customer_id AND pe.campo = en.campo
    WHERE en.valor IS NOT NULL
      AND en.valor IS DISTINCT FROM pe.valor_base

  ), calculado AS (
    SELECT o.customer_id,
           coalesce(o.erp_id, c.erp_id) AS erp_id,
           public.espejo_valor(o.nit,          c.nit,          o.prot, 'nit')          AS nit,
           public.espejo_valor(o.dui,          c.dui,          o.prot, 'dui')          AS dui,
           public.espejo_valor(o.nrc,          c.nrc,          o.prot, 'nrc')          AS nrc,
           public.espejo_valor(o.phone,        c.phone,        o.prot, 'phone')        AS phone,
           public.espejo_valor(o.telefono2,    c.telefono2,    o.prot, 'telefono2')    AS telefono2,
           public.espejo_valor(o.email,        c.email,        o.prot, 'email')        AS email,
           public.espejo_valor(o.direccion,    c.direccion,    o.prot, 'direccion')    AS direccion,
           public.espejo_valor(o.pasaporte,    c.pasaporte,    o.prot, 'pasaporte')    AS pasaporte,
           public.espejo_valor(o.departamento, c.departamento, o.prot, 'departamento') AS departamento,
           public.espejo_valor(o.municipio,    c.municipio,    o.prot, 'municipio')    AS municipio,
           public.espejo_valor(o.distrito,     c.distrito,     o.prot, 'distrito')     AS distrito,
           public.espejo_valor(o.categoria,    c.categoria,    o.prot, 'categoria')    AS categoria,
           public.espejo_valor(o.giro,         c.giro,         o.prot, 'giro')         AS giro,
           public.espejo_valor(o.retencion_pct::text, c.retencion_pct::text,
                               o.prot, 'retencion_pct')::smallint                      AS retencion_pct
    FROM objetivo o
    JOIN public.customers c ON c.id = o.customer_id

  ), ins AS (
    INSERT INTO public.espejo_conflictos
        (customer_id, changelog_id, campo, valor_base, valor_portal, valor_erp)
    SELECT customer_id, changelog_id, campo, valor_base, valor_portal, valor_erp
    FROM conflictos
    RETURNING 1

  -- El guard de IS DISTINCT FROM no es cosmético: sin él cada corrida del
  -- espejo reescribe las ~1,000 filas aunque no haya cambiado nada, que es
  -- exactamente el churn de WAL que el proyecto tiene prohibido en los syncs
  -- recurrentes.
  ), upd AS (
    UPDATE public.customers c SET
        erp_id = k.erp_id, nit = k.nit, dui = k.dui, nrc = k.nrc,
        phone = k.phone, telefono2 = k.telefono2, email = k.email,
        direccion = k.direccion, pasaporte = k.pasaporte,
        departamento = k.departamento, municipio = k.municipio,
        distrito = k.distrito, categoria = k.categoria, giro = k.giro,
        retencion_pct = k.retencion_pct, updated_at = now()
    FROM calculado k
    WHERE c.id = k.customer_id
      AND (c.erp_id, c.nit, c.dui, c.nrc, c.phone, c.telefono2, c.email,
           c.direccion, c.pasaporte, c.departamento, c.municipio, c.distrito,
           c.categoria, c.giro, c.retencion_pct)
          IS DISTINCT FROM
          (k.erp_id, k.nit, k.dui, k.nrc, k.phone, k.telefono2, k.email,
           k.direccion, k.pasaporte, k.departamento, k.municipio, k.distrito,
           k.categoria, k.giro, k.retencion_pct)
    RETURNING 1
  )
  SELECT json_build_object(
    'recibidas',           (SELECT count(*) FROM filas),
    'duplicadas_omitidas', (SELECT coalesce(sum(n), 0) FROM conteo WHERE n > 1),
    'actualizadas',        (SELECT count(*) FROM upd),
    'sin_cambio',          (SELECT count(*) FROM objetivo) - (SELECT count(*) FROM upd),
    'campos_protegidos',   (SELECT count(*) FROM entrantes en
                            JOIN pendientes pe ON pe.customer_id = en.customer_id
                                              AND pe.campo = en.campo
                            WHERE en.valor IS NOT DISTINCT FROM pe.valor_base),
    'conflictos',          (SELECT count(*) FROM ins),
    'sin_match',           (SELECT count(*) FROM unicas e
                            WHERE NOT EXISTS (SELECT 1 FROM public.customers c
                                              WHERE c.search_name = e.match_name))
  ) INTO v_resultado;

  RETURN v_resultado;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.aplicar_espejo_erp(json) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.aplicar_espejo_erp(json) TO authenticated, service_role;
