-- Bolsas de efectivo — F1: la bolsa nace de un corte confirmado.
--
-- Entre «el corte cuadro» y «el dinero llego a administracion» hoy no hay
-- ningun registro. Ese hueco dura hasta tres dias, contiene el efectivo de seis
-- salas, y adentro se le saca dinero dejando un papel suelto. La bolsa es el
-- objeto que falta.
--
-- Definicion completa: docs/PLAN-BOLSAS-DE-EFECTIVO-2026-08-15.md
--
-- Por que un descuadre de bolsa NO lo puede ver el corte: cuando sacan $200 y
-- dejan el papel, el papel ocupa el lugar del billete y el corte siguiente sigue
-- cuadrando. Ninguna cuenta que el portal ya hace lo detecta.
--
-- Esta migracion toca `cortes_caja`, que recibe escrituras del cron de captura
-- cada 30 segundos: la FK necesita un lock sobre esa tabla. Por eso el
-- lock_timeout — si falla, se reintenta; no congela produccion.
--
-- Probada primero en el branch de staging (cbnjplmnfmfsambavjce): la aritmetica
-- de `bolsa_sugerida` se verifico contra un dia real de 2 cortes confirmados en
-- una transaccion revertida — 654.00 + 558.00 = 1212.00, el declarado del ultimo
-- corte, que es el invariante del sistema.

SET lock_timeout = '5s';

-- ── La bolsa ────────────────────────────────────────────────────────────────
--
-- El folio es una secuencia global (`B-1042`) y NO codifica la sala a proposito.
-- Un prefijo tipo `S3-` o `B27-` invita a leer un numero como si fuera el numero
-- de la sala, que es un error que este proyecto ya cometio (ver la memoria
-- `feedback_la_numeracion_de_sala_del_erp_no_es_su_nombre`). La sala va impresa
-- en letras en la etiqueta, que es como se ordenan las bolsas sobre la mesa; el
-- folio sirve para buscarla y para eso solo tiene que ser corto y unico.
CREATE SEQUENCE IF NOT EXISTS public.bolsas_folio_seq START 1000;

CREATE TABLE IF NOT EXISTS public.bolsas (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio               text        NOT NULL UNIQUE,
    branch_id           bigint      NOT NULL REFERENCES public.branches(id),
    corte_id            bigint      REFERENCES public.cortes_caja(id),
    origen              text        NOT NULL DEFAULT 'CORTE'
                                    CHECK (origen IN ('CORTE','MANUAL')),
    motivo_origen       text,
    -- El efectivo que se guardo. Lo calcula el SERVIDOR (`bolsa_sugerida`): es
    -- la cifra contra la que despues se le reclama a alguien.
    monto_inicial       numeric(12,2) NOT NULL CHECK (monto_inicial > 0),
    -- La fecha y la hora del CORTE, no las del cierre de la bolsa: es como la
    -- sala la nombra («la del corte de las siete»), y es lo que ordena la serie
    -- del dia para calcular cuanto falta por embolsar.
    fecha               date        NOT NULL,
    hora                time        NOT NULL,
    caja                text,
    cerrada_por         uuid        REFERENCES public.employees(id),
    cerrada_at          timestamptz NOT NULL DEFAULT now(),
    estado              text        NOT NULL DEFAULT 'ABIERTA'
                                    CHECK (estado IN ('ABIERTA','ENTREGADA','RECIBIDA','CONTADA','ANULADA')),
    -- Cuantas veces se imprimio su etiqueta. La etiqueta se vuelve mentira en
    -- cuanto sale plata de la bolsa, y sobre la mesa dos etiquetas de la misma
    -- bolsa se ven iguales: por eso cada impresion va numerada y dice que anula
    -- a la anterior.
    etiqueta_version    integer     NOT NULL DEFAULT 0,
    etiqueta_impresa_at timestamptz,
    anulada_por         uuid        REFERENCES public.employees(id),
    anulada_motivo      text,
    anulada_at          timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT bolsas_corte_tiene_corte
        CHECK (origen <> 'CORTE' OR corte_id IS NOT NULL),
    CONSTRAINT bolsas_manual_tiene_motivo
        CHECK (origen <> 'MANUAL' OR nullif(btrim(coalesce(motivo_origen,'')),'') IS NOT NULL)
);

COMMENT ON TABLE public.bolsas IS
    'El efectivo que una sala guarda al confirmar un corte, hasta que administracion lo cuenta.';

-- Una bolsa viva por corte. Parcial y no unique a secas: una anulada no puede
-- impedir que se vuelva a cerrar la bolsa de ese corte.
CREATE UNIQUE INDEX IF NOT EXISTS bolsas_corte_viva
    ON public.bolsas(corte_id) WHERE corte_id IS NOT NULL AND estado <> 'ANULADA';
CREATE INDEX IF NOT EXISTS bolsas_branch_estado ON public.bolsas(branch_id, estado);
CREATE INDEX IF NOT EXISTS bolsas_fecha         ON public.bolsas(fecha DESC);
CREATE INDEX IF NOT EXISTS bolsas_cerrada_por   ON public.bolsas(cerrada_por);

ALTER TABLE public.bolsas ENABLE ROW LEVEL SECURITY;

-- Las escrituras van SOLO por las funciones DEFINER de abajo: sin policy de
-- INSERT/UPDATE/DELETE nadie escribe directo, que es lo que hace que el monto
-- no lo pueda elegir el navegador.
DROP POLICY IF EXISTS bolsas_select ON public.bolsas;
CREATE POLICY bolsas_select ON public.bolsas
    FOR SELECT TO authenticated
    USING (
        (SELECT auth_has_module_permission('bolsas','can_view'))
        AND ((SELECT auth_module_scope('bolsas')) = 'ALL'
             OR branch_id = (SELECT auth_employee_branch_id()))
    );

DROP POLICY IF EXISTS bloqueo_global ON public.bolsas;
CREATE POLICY bloqueo_global ON public.bolsas
    AS RESTRICTIVE FOR ALL TO public
    USING ((SELECT auth_no_bloqueado()));

REVOKE ALL ON public.bolsas FROM anon;
GRANT SELECT ON public.bolsas TO authenticated;
GRANT ALL ON public.bolsas TO service_role;

-- ── Cuanto falta por embolsar ───────────────────────────────────────────────
--
-- Los cortes son ACUMULATIVOS dentro del dia: el de la noche contiene al de la
-- manana. Entonces lo que entra a la bolsa del corte N es lo declarado en N
-- menos lo que ya se embolso antes de su hora.
--
--     sugerida(N) = declarado(N) − suma(bolsas vivas de esa sala y ese dia
--                                        con hora < hora(N))
--
-- Se mide contra las BOLSAS y no contra el corte confirmado anterior a
-- proposito: si un corte se confirmo y nadie embolso, ese efectivo sigue en el
-- cajon y tiene que entrar completo a la bolsa siguiente. Restar el corte
-- anterior daria de menos y dejaria dinero sin registrar.
--
-- Medido en los 24 cortes confirmados del 13 y 14 de agosto: los 24 incrementos
-- dan positivo, de $145.27 a $1,272.92. Consistente, no probado — lo prueba la
-- primera bolsa real contada contra su etiqueta.
--
-- Los $150 del fondo de cambio NO entran: lo que el corte espera es
-- `ingresos + venta − vales + cobros`, puro movimiento del dia, sin termino de
-- fondo (`tk_saldo_inicial` viene en 0.00 en todas las filas capturadas). El
-- fondo vive afuera del corte y por lo tanto afuera de la bolsa.
CREATE OR REPLACE FUNCTION public.bolsa_sugerida(p_corte_id bigint)
RETURNS numeric
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT round(c.total_declarado - coalesce((
        SELECT sum(b.monto_inicial)
          FROM public.bolsas b
         WHERE b.branch_id = c.branch_id
           AND b.fecha     = c.fecha
           AND b.estado   <> 'ANULADA'
           AND b.hora      < c.hora
    ), 0), 2)
      FROM public.cortes_caja c
     WHERE c.id = p_corte_id;
$$;

REVOKE EXECUTE ON FUNCTION public.bolsa_sugerida(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.bolsa_sugerida(bigint) TO authenticated, service_role;

-- ── Los cortes que esperan su bolsa ─────────────────────────────────────────
--
-- Es la lista que ve la sala y, de paso, el invariante del sistema en forma de
-- pantalla: si un corte confirmado no tiene bolsa, o falta guardar el dinero o
-- falta registrarlo. Detecta el caso peor — efectivo contado que nunca se
-- guardo.
CREATE OR REPLACE FUNCTION public.get_cortes_por_embolsar(p_desde date, p_hasta date)
RETURNS TABLE (
    corte_id        bigint,
    branch_id       bigint,
    fecha           date,
    hora            time,
    caja            text,
    total_declarado numeric,
    sugerida        numeric
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT c.id, c.branch_id, c.fecha, c.hora, c.empleado_texto, c.total_declarado,
           public.bolsa_sugerida(c.id)
      FROM public.cortes_caja c
     WHERE (SELECT auth_has_module_permission('bolsas','can_view'))
       AND c.tipo   = 'C'
       AND c.estado = 'CONFIRMADO'
       AND c.fecha BETWEEN p_desde AND p_hasta
       AND ((SELECT auth_module_scope('bolsas')) = 'ALL'
            OR c.branch_id = (SELECT auth_employee_branch_id()))
       AND NOT EXISTS (
           SELECT 1 FROM public.bolsas b
            WHERE b.corte_id = c.id AND b.estado <> 'ANULADA')
       AND public.bolsa_sugerida(c.id) > 0
     ORDER BY c.fecha DESC, c.branch_id, c.hora;
$$;

REVOKE EXECUTE ON FUNCTION public.get_cortes_por_embolsar(date, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_cortes_por_embolsar(date, date) TO authenticated, service_role;

-- ── Cerrar la bolsa ─────────────────────────────────────────────────────────
--
-- `p_monto_esperado` es lo que se vio en pantalla y NO es lo que se guarda: el
-- servidor calcula el suyo y rechaza si no coinciden. Es la misma regla que
-- `resolver_diferencia_corte`, por el mismo motivo — si el monto lo manda el
-- navegador, cualquiera elige cuanto dinero dice haber guardado.
--
-- Cerrar la bolsa es un acto FISICO de una persona, por eso es un paso aparte
-- de confirmar el corte y no un efecto automatico. Si se creara sola, el
-- registro diria que hay una bolsa donde a lo mejor no la hay.
CREATE OR REPLACE FUNCTION public.cerrar_bolsa_de_corte(
    p_corte_id       bigint,
    p_monto_esperado numeric
)
RETURNS public.bolsas
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_corte  public.cortes_caja;
    v_bolsa  public.bolsas;
    v_scope  text;
    v_monto  numeric;
BEGIN
    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas'])) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    SELECT * INTO v_corte FROM public.cortes_caja WHERE id = p_corte_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'El corte no existe.';
    END IF;

    -- La funcion es DEFINER, asi que no pasa por la policy de la tabla: quien
    -- ve solo su sala no cierra la bolsa de otra.
    v_scope := (SELECT auth_module_scope('bolsas'));
    IF v_scope IS DISTINCT FROM 'ALL'
       AND v_corte.branch_id IS DISTINCT FROM (SELECT auth_employee_branch_id()) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    IF v_corte.tipo <> 'C' THEN
        RAISE EXCEPTION 'El cierre del dia no lleva bolsa.';
    END IF;

    -- Un corte sin confirmar puede rehacerse, y entonces su monto cambia. La
    -- bolsa se cierra sobre una cifra firmada.
    IF v_corte.estado <> 'CONFIRMADO' THEN
        RAISE EXCEPTION 'Primero hay que confirmar el corte.';
    END IF;

    IF EXISTS (SELECT 1 FROM public.bolsas b
                WHERE b.corte_id = p_corte_id AND b.estado <> 'ANULADA') THEN
        RAISE EXCEPTION 'Este corte ya tiene su bolsa.';
    END IF;

    v_monto := public.bolsa_sugerida(p_corte_id);

    IF v_monto IS NULL OR v_monto <= 0 THEN
        RAISE EXCEPTION 'No queda efectivo por guardar de este corte: las bolsas de la sala ya cubren lo declarado.';
    END IF;

    IF round(coalesce(p_monto_esperado, -1), 2) <> v_monto THEN
        RAISE EXCEPTION 'El monto cambio mientras estabas en la pantalla: ahora son % y en pantalla decia %. Volve a abrirla.',
            to_char(v_monto, 'FM999999990.00'),
            to_char(round(coalesce(p_monto_esperado, 0), 2), 'FM999999990.00');
    END IF;

    INSERT INTO public.bolsas
        (folio, branch_id, corte_id, origen, monto_inicial, fecha, hora, caja, cerrada_por)
    VALUES
        ('B-' || nextval('public.bolsas_folio_seq'),
         v_corte.branch_id, p_corte_id, 'CORTE', v_monto,
         v_corte.fecha, v_corte.hora, v_corte.empleado_texto,
         (SELECT auth_employee_id()))
    RETURNING * INTO v_bolsa;

    RETURN v_bolsa;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.cerrar_bolsa_de_corte(bigint, numeric) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.cerrar_bolsa_de_corte(bigint, numeric) TO authenticated, service_role;

-- ── La etiqueta impresa ─────────────────────────────────────────────────────
--
-- Sube el numero y devuelve el que quedo, para que el papel diga «ETIQUETA #3 -
-- ANULA LA ANTERIOR». No promete que salio papel: la respuesta de la ticketera
-- es opaca por construccion, asi que se puede marcar tantas veces como se
-- reimprima.
CREATE OR REPLACE FUNCTION public.marcar_etiqueta_impresa(p_bolsa_id bigint)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_scope text;
    v_branch bigint;
    v_version integer;
BEGIN
    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas'])) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    SELECT branch_id INTO v_branch FROM public.bolsas WHERE id = p_bolsa_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'La bolsa no existe.';
    END IF;

    v_scope := (SELECT auth_module_scope('bolsas'));
    IF v_scope IS DISTINCT FROM 'ALL'
       AND v_branch IS DISTINCT FROM (SELECT auth_employee_branch_id()) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    UPDATE public.bolsas
       SET etiqueta_version    = etiqueta_version + 1,
           etiqueta_impresa_at = now(),
           updated_at          = now()
     WHERE id = p_bolsa_id
     RETURNING etiqueta_version INTO v_version;

    RETURN v_version;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.marcar_etiqueta_impresa(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.marcar_etiqueta_impresa(bigint) TO authenticated, service_role;

-- ── Anular una bolsa ────────────────────────────────────────────────────────
--
-- Se anula, nunca se borra: la etiqueta ya salio y esta pegada a una bolsa. Solo
-- mientras siga en la sala — una vez entregada, quien la tiene es otro.
CREATE OR REPLACE FUNCTION public.anular_bolsa(p_id bigint, p_motivo text)
RETURNS public.bolsas
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_bolsa public.bolsas;
    v_scope text;
BEGIN
    IF NOT (SELECT auth_can_edit_any(ARRAY['bolsas'])) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    IF p_motivo IS NULL OR btrim(p_motivo) = '' THEN
        RAISE EXCEPTION 'Anular una bolsa exige decir por que.';
    END IF;

    SELECT * INTO v_bolsa FROM public.bolsas WHERE id = p_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'La bolsa no existe.';
    END IF;

    v_scope := (SELECT auth_module_scope('bolsas'));
    IF v_scope IS DISTINCT FROM 'ALL'
       AND v_bolsa.branch_id IS DISTINCT FROM (SELECT auth_employee_branch_id()) THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    IF v_bolsa.estado <> 'ABIERTA' THEN
        RAISE EXCEPTION 'Esta bolsa ya salio de la sala: no se puede anular.';
    END IF;

    UPDATE public.bolsas
       SET estado         = 'ANULADA',
           anulada_por    = (SELECT auth_employee_id()),
           anulada_motivo = btrim(p_motivo),
           anulada_at     = now(),
           updated_at     = now()
     WHERE id = p_id
     RETURNING * INTO v_bolsa;

    RETURN v_bolsa;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.anular_bolsa(bigint, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.anular_bolsa(bigint, text) TO authenticated, service_role;

-- ── Permisos ────────────────────────────────────────────────────────────────
--
-- Calcados de `cortes_caja`: las salas cierran sus propias bolsas, igual que
-- confirman sus propios cortes (decision del usuario, 2026-08-14). El widget va
-- aparte para poder apagarlo sin quitar el modulo.
INSERT INTO public.role_permissions (role_id, module_key, can_view, can_edit, can_approve, scope)
SELECT rp.role_id, m.key, rp.can_view, rp.can_edit, false, rp.scope
  FROM public.role_permissions rp
 CROSS JOIN (VALUES ('bolsas'), ('dash_bolsas_sala')) AS m(key)
 WHERE rp.module_key = 'cortes_caja'
ON CONFLICT (role_id, module_key) DO NOTHING;
